DROP TABLE IF EXISTS instituicoes;

CREATE TABLE instituicoes (
    NO_REGIAO TEXT,
    CO_REGIAO TEXT,
    NO_UF TEXT,
    SG_UF TEXT,
    CO_UF TEXT,
    NO_MUNICIPIO TEXT,
    CO_MUNICIPIO TEXT,
    NO_MESORREGIAO TEXT,
    NO_MICRORREGIAO TEXT,
    NO_ENTIDADE TEXT NOT NULL,
    CO_ENTIDADE INTEGER NOT NULL UNIQUE,
    QT_MAT_BAS INTEGER NOT NULL CHECK (QT_MAT_BAS >= 0),
    QT_MAT_INF INTEGER,
    QT_MAT_FUND INTEGER,
    QT_MAT_MED INTEGER,
    QT_MAT_EJA INTEGER,
    QT_MAT_EJA_FUND INTEGER,
    QT_MAT_ESP INTEGER,
    QT_MAT_BAS_EAD INTEGER,
    QT_MAT_FUND_INT INTEGER,
    QT_MAT_MED_INT INTEGER,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_co_entidade ON instituicoes(CO_ENTIDADE);
